/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace RelicRushRunLedger {
      
    export type RunSummaryStruct = {floorReached: BigNumberish, score: BigNumberish, timestamp: BigNumberish}

    export type RunSummaryStructOutput = [floorReached: bigint, score: bigint, timestamp: bigint] & {floorReached: bigint, score: bigint, timestamp: bigint }
  
    }

  export interface RelicRushRunLedgerInterface extends Interface {
    getFunction(nameOrSignature: "bestScore" | "getRun" | "recordRun" | "runCount" | "runs"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RunRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'bestScore', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getRun', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordRun', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'runCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'runs', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'bestScore', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRun', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordRun', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'runCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'runs', data: BytesLike): Result;
  }

  
    export namespace RunRecordedEvent {
      export type InputTuple = [player: AddressLike, floorReached: BigNumberish, score: BigNumberish];
      export type OutputTuple = [player: string, floorReached: bigint, score: bigint];
      export interface OutputObject {player: string, floorReached: bigint, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RelicRushRunLedger extends BaseContract {
    
    connect(runner?: ContractRunner | null): RelicRushRunLedger;
    waitForDeployment(): Promise<this>;

    interface: RelicRushRunLedgerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    bestScore: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getRun: TypedContractMethod<
      [player: AddressLike, index: BigNumberish, ],
      [RelicRushRunLedger.RunSummaryStructOutput],
      'view'
    >
    

    
    recordRun: TypedContractMethod<
      [floorReached: BigNumberish, score: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    runCount: TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    runs: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint] & {floorReached: bigint, score: bigint, timestamp: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bestScore'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRun'): TypedContractMethod<
      [player: AddressLike, index: BigNumberish, ],
      [RelicRushRunLedger.RunSummaryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'recordRun'): TypedContractMethod<
      [floorReached: BigNumberish, score: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'runCount'): TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'runs'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [[bigint, bigint, bigint] & {floorReached: bigint, score: bigint, timestamp: bigint }],
      'view'
    >;

    getEvent(key: 'RunRecorded'): TypedContractEvent<RunRecordedEvent.InputTuple, RunRecordedEvent.OutputTuple, RunRecordedEvent.OutputObject>;

    filters: {
      
      'RunRecorded(address,uint32,uint32)': TypedContractEvent<RunRecordedEvent.InputTuple, RunRecordedEvent.OutputTuple, RunRecordedEvent.OutputObject>;
      RunRecorded: TypedContractEvent<RunRecordedEvent.InputTuple, RunRecordedEvent.OutputTuple, RunRecordedEvent.OutputObject>;
    
    };
  }